name: Deploy to Staging

on:
  workflow_call:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        id: install-kubectl

      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.KUBE_CONFIG_STAGING}}

      - name: Deploy to the Kubernetes cluster (staging)
        run: |
          ${{ steps.install-kubectl.outputs.kubectl-path }} rollout restart deploy power-web-depl -n powerkernel-dev
