# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Feature

on:
  pull_request:
    branches: [main]

jobs:
  install:
    uses: powerkernel/actions-workflows/.github/workflows/install-npm.yml@main

  test:
    needs: install
    uses: ./.github/workflows/testing.yml

  build:
    needs: test
    uses: powerkernel/actions-workflows/.github/workflows/build-feature.yml@main
    with:
      username: ${{ github.actor }}
      password: ${{ github.token }}
