# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node CI

on:
  push:
    branches: [main]
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (staging)
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            NODE_AUTH_TOKEN=${{secrets.NODE_AUTH_TOKEN}}
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ghcr.io/${{github.repository}}:main

      - name: Build and push (prod)
        if: github.ref_name != 'main'
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            NODE_AUTH_TOKEN=${{secrets.NODE_AUTH_TOKEN}}
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ghcr.io/${{github.repository}}:${{github.ref_name}},ghcr.io/${{github.repository}}:latest
