# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  install:
    uses: powerkernel/actions-workflows/.github/workflows/install-npm.yml@main

  test:
    needs: install
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    uses: ./.github/workflows/_build-pr.yml
