# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node CI Production

on:
  push:
    tags: [v*]

jobs:
  install:
    uses: ./.github/workflows/install.yml

  test:
    needs: install
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    uses: ./.github/workflows/build-prod.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-prod.yml
    secrets: inherit
